#!/bin/bash
sqlite3 inventory.db << EOF
CREATE TABLE items (
  upc TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  image TEXT,
  count INTEGER
);

CREATE TABLE groceries (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  item TEXT NOT NULL,
  date_added DATE,
  exp_date DATE,
  FOREIGN KEY (item) REFERENCES items(upc)
);
EOF
